import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export const generateComplaintPDF = (complaint, user) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument();
    const filename = `complaint-${complaint._id}-${Date.now()}.pdf`;
    const uploadsDir = path.join(__dirname, '../uploads');
    const filepath = path.join(uploadsDir, filename);

    // Ensure uploads directory exists
    if (!fs.existsSync(uploadsDir)) {
      fs.mkdirSync(uploadsDir, { recursive: true });
    }
    
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);

    // Header
    doc.fontSize(20).text('OFFICIAL CIVIC COMPLAINT', 50, 50);
    doc.fontSize(12).text(`Generated by NeighbourFix Platform`, 50, 80);
    doc.moveDown();

    // Complaint Details
    doc.fontSize(14).text('COMPLAINT DETAILS', { underline: true });
    doc.fontSize(12);
    doc.text(`Complaint ID: ${complaint._id}`);
    doc.text(`Date Reported: ${complaint.createdAt.toLocaleDateString()}`);
    doc.text(`Category: ${complaint.category.toUpperCase()}`);
    doc.text(`Status: ${complaint.status.toUpperCase()}`);
    doc.text(`Upvotes Received: ${complaint.upvotes}`);
    doc.moveDown();

    // Location
    doc.fontSize(14).text('LOCATION', { underline: true });
    doc.fontSize(12);
    doc.text(`Ward Number: ${complaint.wardNumber}`);
    doc.text(`Address: ${complaint.address || 'Not provided'}`);
    doc.text(`GPS Coordinates: ${complaint.location.coordinates[1]}, ${complaint.location.coordinates[0]}`);
    doc.moveDown();

    // Description
    doc.fontSize(14).text('ISSUE DESCRIPTION', { underline: true });
    doc.fontSize(12).text(complaint.description);
    doc.moveDown();

    // Reporter Info
    doc.fontSize(14).text('REPORTED BY', { underline: true });
    doc.fontSize(12);
    doc.text(`Name: ${user.name}`);
    doc.text(`Email: ${user.email}`);
    doc.text(`Phone: ${user.phone || 'Not provided'}`);
    doc.moveDown();

    // Footer
    doc.fontSize(10).text('This is an auto-generated complaint from NeighbourFix. Please take necessary action.', 50, 700);
    doc.text(`Generated on: ${new Date().toLocaleString()}`);

    doc.end();

    stream.on('finish', () => resolve(filepath));
    stream.on('error', reject);
  });
};

export default { generateComplaintPDF };